<div class="box-login">
    <h3><?php echo $title_for_layout; ?></h3>
    <p>&nbsp;</p>

    <form class="form-login" action="" method="POST" enctype="multipart/form-data">
        <?php echo $this->flashSession->output(); ?>

        <fieldset>
            <div class="form-group">
                <span class="input-icon">
                    <?php echo $form->render('username', array('class' => 'form-control', 'placeholder' => 'Tên đăng nhập')); ?>
                    <?php echo $this->partial('admin/element/layout/_message', array('form' => $form, 'element' => 'username')); ?>
                    <i class="fa fa-user"></i>
                </span>
            </div>
            <div class="form-group form-actions">
                <span class="input-icon">
                    <?php echo $form->render('password', array('class' => 'form-control password', 'placeholder' => 'Mật khẩu')); ?>
                    <?php echo $this->partial('admin/element/layout/_message', array('form' => $form, 'element' => 'password')); ?>
                    <i class="fa fa-lock"></i>
                </span>
            </div>
            <div class="form-actions">
                <button type="submit" class="btn btn-bricky pull-right">
                    Đăng nhập <i class="fa fa-arrow-circle-right"></i>
                </button>
            </div>
        </fieldset>

        <input type="hidden" name="<?php echo $this->security->getTokenKey(); ?>" value="<?php echo $this->security->getToken(); ?>">
    </form>
</div>