
<?php
$query = array(
    'page' => $page,
    'q' => $q,
    'cache_name' => $cache_name,
    'group_cache_name' => $group_cache_name
);
?>
<div class="container">
    <?php echo $this->partial('element/layout/_breadcrumbs'); ?>
    <?php echo $this->flashSession->output(); ?>
    <div class="text-right">
        <a class="btn btn-primary" href="<?php echo $this->url->get(array('for' => 'link_group_add', 'query' => '?' . http_build_query($query))); ?>"> Thêm nhóm liên kết </a>
    </div>
    <p></p>
    <?php echo $this->partial('link/_list'); ?>
    <?php
    echo $this->partial('element/layout/_pagination', array(
        'result' => $result,
        'for' => 'link_group_list',
        'query' => array(
            'page' => $page, 
            'q' => $q
        )
    ));
    ?>
</div>