<?php use ITECH\Datasource\Lib\Util; ?>

<section id="section2">
  <div class="container">
    <div class="row">
        <?php echo $this->partial($__theme. '/element/layout/_breadcrumbs', array('breadcrumbs' => $breadcrumbs)); ?>
        <div class="col-sm-8 col-md-8 congso-main-content post-info-block">
            <div class="main-post-body">
            <!-- BANNER 2 -->
                <?php echo Util::itemAds(1, $premiumList); ?>
                <h3 class="post-title">
                  <?php echo $article->title; ?>
                </h3>
                <div class="under-title">
                    <div class="date-created">
                        Đăng bởi 
                        <b>
                            <?php $slug_admin = Util::slug($name_admin->name); ?>       
                            <a href="<?php echo $this->url->get(array('for' => 'article_list_member', 'id' => $name_admin->id, 'slug' => $slug_admin)); ?>" title="<?php echo $name_admin->name; ?>">
                                <?php echo $name_admin->name; ?>
                            </a>
                        </b> | <?php echo date('d/m/Y', $article->updated_at); ?> | <span class="analytics"><?php echo $article->hits; ?></span>
                    </div>
                </div>
                <div class="post-info-description">
                  <?php echo $article->intro; ?>
                </div>
                <div class="congso-post">
                    <!-- BANNER 3 -->
                    <?php
                        $contentss = Util::itemAds(2, $premiumList);
                        echo Util::ad_content($article_content->content, $contentss);
                    ?>
                    <!-- BANNER 4 -->
                    <?php echo Util::itemAds(3, $premiumList); ?>
                    <div class="clearfix"></div>
                    
                    <span class="btn btn-default btn-xs pull-right" style="padding: 6px;font-style: italic;">
                        Đăng bởi <?php echo $name_admin->name; ?>
                    </span>
                
                    <div class="clearfix"></div>
                    Tags:
                    <?php $tag = array(); ?>
                    <?php foreach ($tags as $item): ?>
                    <?php $tag[] = '<a href="' . $this->url->get(array('for' => 'article_list_tag', 'slug' => $item->tag_slug)). '">' . $item->tag_title . '</a>'; ?>
                    <?php endforeach; ?>
                    <?php echo implode(', ', $tag); ?>
                    <div class="clearfix"></div>
                    
                    <?php if ($newer_layout != ''): ?>
                        <div class="congso-post-related">
                            <?php echo $newer_layout; ?>
                        </div>
                        <div class="clearfix"></div>
                    <?php endif; ?>
                    <!-- BANNER 5 -->
                        <?php echo Util::itemAds(4, $premiumList); ?>
                    <?php if ($older_layout != ''): ?>
                        <div class="congso-post-related">
                            <?php echo $older_layout; ?>
                        </div>
                    <?php endif; ?>
                </div>
                <div class="clearfix"></div>
                
            </div>
        </div>
        <div class="col-sm-4 col-md-4 congso-main-aside">
            <div class="congso-aside-block">
                <h2 class="aside-title">Tin mới nhất</h2>
                <?php echo $most_new_layout; ?>
            </div>
            <div class="congso-aside-block">
                <h2 class="aside-title">Tin xem nhiều nhất</h2>
                <?php echo $most_viewed_layout; ?>
            </div>
            <?php if(!$article_content->title_content_h2=='' && !$article_content->content2_h2 ==''){?>
             <div class="congso-aside-block" style="border: #d7d7d7 solid 1px;border-radius: 6px;margin-bottom: 30px;line-height: 1.3;">
                     <h2 style="font-size: 15px;max-width:280px;font-weight:bold;margin-top: 10px;margin-left:10px;"><?php echo $article_content->title_content_h2; ?></h2>
                        <div style="font: 13px; max-width: 280px;margin-left:10px;"><?php echo Util::filterHtmlTag($article_content->content2_h2); ?></div>
                </div>
                <?php } ?>
                <?php if(!$article_content->title_content_h3=='' && !$article_content->content2_h3 ==''){?>
                <div class="clearfix"></div>

                 <div class="congso-aside-block" style="border: #d7d7d7 solid 1px;border-radius: 6px;margin-bottom: 30px;    line-height: 1.3;">
                    <h3 style="font-size: 15px;max-width:280px;font-weight:bold;margin-top: 10px;margin-left:10px;"><?php echo $article_content->title_content_h3; ?></h3>
                    <div style="font: 13px; max-width: 290px;margin-left:10px;"><?php echo Util::filterHtmlTag($article_content->content2_h3); ?></div>
                </div>
                <?php } ?>
            <div class="">
                <?php echo $link_box_four_layout; ?>
            </div>
        </div>
        <div class="clearfix"></div>
        <?php if (isset($listPostApi)): ?>
        <?php echo $listPostApi ? $listPostApi : '' ?>
        <?php endif; ?>
        <div class="col-sm-12 col-md-12 congso-main-content">
            <h2 class="fresh-title">Tin nổi bật</h2>
            <?php echo $category_fresh_layout; ?>
        </div>
        <div class="clearfix"></div>
        <div class="col-sm-12 col-md-12 congso-main-content">
            <div class="row congso-list-sub-block">
                <?php if ($categories_detail && count($categories_detail) > 0): ?>
                    <?php $i = 1 ; ?>
                    <?php foreach ($categories_detail as $item): ?>
                        <div class="col-lg-4 col-md-4 col-sm-4 box-home">
                            <div class="congso-sub-block">
                                <?php if(isset($box_layout[$item->id])): ?>
                                <?php echo $box_layout[$item->id]; ?>
                                <?php endif; ?>
                            </div>
                        </div>
                        <?php if ($i % 3 == 0): ?>
                            <div class="clearfix"></div>
                        <?php endif; ?>
                        <?php $i ++ ; ?>
                    <?php endforeach; ?>
                <?php endif; ?>
            </div>
        </div>
    </div>
</section>
<script>
    $(window).load(function(){
        $('.main-post-image,.highlight-image,.main-item-image').each(function(){
            var ratio = $(this).data('ratio');
            var width = $(this).width();
            $(this).height(width/ratio);
        });
    });
    $(window).resize(function(){
      $('.main-post-image,.highlight-image,main-item-image').each(function(){
        var ratio = $(this).data('ratio');
        var width = $(this).width();
        $(this).height(width/ratio);
    });
  });
</script>
