<?php use ITECH\Datasource\Lib\Constant; ?>
<?php use ITECH\Datasource\Model\ArticleAttribute;?>
<?php $attribule_select = Constant::elementFormSelect(); ?>
<div class="row">
    <div class="col-md-9">
        <div class="form-group">
            <label class="col-sm-2 control-label">
                Tiêu đề
            </label>
            <div class="col-sm-10">
                <?php echo $form->render('title', array('class' => 'form-control')); ?>
                <?php echo $this->partial('element/layout/_message', array('form' => $form, 'element' => 'title')); ?>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">
                Giới thiệu
            </label>
            <div class="col-sm-10">
                <?php echo $form->render('intro', array('class' => 'form-control')); ?>
                <?php echo $this->partial('element/layout/_message', array('form' => $form, 'element' => 'intro')); ?>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">
                Meta title
            </label>
            <div class="col-sm-10">
                    <?php echo $form->render('meta_title', array('class' => 'form-control h150')); ?>
                <?php echo $this->partial('element/layout/_message', array('form' => $form, 'element' => 'meta_title')); ?>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">
                Meta Description
            </label>
            <div class="col-sm-10">
                <?php echo $form->render('meta_description', array('class' => 'form-control h150')); ?>
                <?php echo $this->partial('element/layout/_message', array('form' => $form, 'element' => 'meta_description')); ?>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">
                Meta Keyword
            </label>
            <div class="col-sm-10">
                <?php echo $form->render('meta_keyword', array('class' => 'form-control h150')); ?>
                <?php echo $this->partial('element/layout/_message', array('form' => $form, 'element' => 'meta_keyword')); ?>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">
                Nội dung
            </label>
            <div class="col-sm-10">
                <?php echo $form->render('content', array('class' => 'form-control editor', 'id' => 'editor')); ?>
                <?php echo $this->partial('element/layout/_message', array('form' => $form, 'element' => 'content')); ?>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">
                Tags
            </label>
            <div class="col-sm-10">
                <?php echo $form->render('tags', array('class' => 'form-control','id' => 'tag-string')); ?>
                <?php echo $this->partial('element/layout/_message', array('form' => $form, 'element' => 'tags')); ?>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">
                Kiểu trang tĩnh
            </label>
            <div class="col-sm-4">
                <?php echo $form->render('type', array('class' => 'form-control')); ?>
                <?php echo $this->partial('element/layout/_message', array('form' => $form, 'element' => 'type')); ?>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">
                Trạng thái
            </label>
            <div class="col-sm-4">
                <?php echo $form->render('status', array('class' => 'form-control')); ?>
                <?php echo $this->partial('element/layout/_message', array('form' => $form, 'element' => 'status')); ?>
            </div>
        </div> 
    </div>
    <div class="col-md-3"> 
        <div class="panel panel-default">
            <div class="panel-heading">
                <i class="fa fa-external-link-square"></i>
                Hình ảnh đại diện
            </div>
            <div class="panel-body">
                <div class="form-group">
                    <div class="col-sm-12 text-center">
                        <?php if (isset($article)): ?>    
                            <?php if ($article->image != ''): ?>
                                <?php
                                $query = array(
                                    'id' => $article->id,
                                    'page' => $page,
                                    'q' => $q,
                                    'cache_name' => $cache_name
                                );
                                ?> 
                                <img class="thumbnail" style="width:100%" src="<?php echo $this->config->asset->home_image_url . '150/' . $article->image; ?>">
                                <p></p>
                                <a href="<?php echo $this->url->get(array('for' => 'page_delete_image', 'query' => '?' . http_build_query($query))); ?>" class="btn btn-primary">
                                    Xóa
                                </a>
                            <?php else: ?>
                                <img src="<?php echo $this->config->asset->home_image_url . 'default.gif'; ?>">
                                <p></p>
                                <div class="col-sm-12 text-center">
                                    <div data-provides="fileupload" class="fileupload fileupload-new">
                                        <span class="btn btn-file btn-light-grey"><i class="fa fa-folder-open-o"></i> <span class="fileupload-new">Chọn file</span><span class="fileupload-exists">Thay đổi</span>
                                            <input type="file" name="thumbnail">
                                        </span>
                                        <span class="fileupload-preview"></span>
                                        <a style="float: none" data-dismiss="fileupload" class="close fileupload-exists" href="#">
                                                &times;
                                        </a>
                                    </div>
                                </div>
                            <?php endif; ?>
                        <?php endif; ?> 
                    </div> 
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <i class="fa fa-external-link-square"></i>
                Gallery
                <div class="panel-tools">
                    <a class="btn btn-xs btn-link panel-collapse collapses" href="#">
                    </a>
                </div>
            </div>
            <div class="panel-body">
                <div class="form-group">
                    <div class="col-sm-12 col-0">
                        <?php if (isset($article_attachments) && !empty($article_attachments)): ?>
                            <?php foreach ($article_attachments as $item): ?>
                                <div class="col-sm-4 col-2">
                                    <img class="thumbnail h50 w80 col-0 m-b-2" style="width:100%" src="<?php echo $this->config->asset->home_image_url . '150/' . $item->file_name; ?>">
                                </div>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </div>
                </div>
                <div class="col-sm-12 text-center">
                    <?php if($article->id && $article->id != ''): ?>
                        <?php
                        $query = array(
                            'id' => $article->id,
                            'page' => $page,
                            'q' => $q,
                            'cache_name' => $cache_name,
                            'from' => 'page'
                        );
                        ?>
                        <a href="<?php echo $this->url->get(array('for' => 'file_gallery', 'query' => '?' . http_build_query($query))); ?>" class="btn btn-primary">
                            Thêm mới
                        </a>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
</div>

