<?php use ITECH\Datasource\Lib\Util; ?>
<?php use ITECH\Datasource\Lib\Constant; ?>
<section id="section2">
    <div class="container">
        <div class="row">
            <?php echo $this->partial($__theme. '/element/layout/_breadcrumbs', array('breadcrumbs' => $breadcrumbs)); ?>
            <div class="header-category col-sm-12">
                <h1 class="category-name">
                    <?php echo $category->name; ?>
                </h1>
            </div>
            <!-- filter-category -->
            <div class="list-post-category col-sm-12">
            <?php if($result): ?>
                <?php foreach ($result->items as $item): ?>
                    <?php 
                        if (!$item->alias):
                            $item->alias = Util::slug($item->title); 
                        endif;
                    ?>
                    <article class="item-post">
                        <div class="info-left post-image list-img">
                            <a href="<?php echo $this->url->get(array('for' => 'article_detail','id' => $item->id, 'slug' => $item->alias)); ?>" class="thumbail-item">
                                <?php $file_headers = @get_headers($this->config->asset->home_image_url . '250/' . $item->image); ?>
                                <?php if ($item->image != '' && $file_headers[0] != 'HTTP/1.1 404 Not Found'): ?>
                                    <img class="fix-ratio" src="<?php echo $this->config->asset->home_image_url . '250/' . $item->image; ?>" alt="<?php echo $item->title; ?>">
                                <?php else: ?>
                                    <img class="fix-ratio" src="<?php echo $this->config->asset->home_image_url . 'default.gif'; ?>" alt="<?php echo $item->title; ?>">
                                <?php endif; ?>
                            </a>
                        </div>
                        <div class="block-info">
                        <a href="<?php echo $this->url->get(array('for' => 'article_detail','id' => $item->id, 'slug' => $item->alias)); ?>" class="post-title">
                        <h2 class="title-post">
                            <?php echo $item->title; ?>
                            </h2>
                        </a>
                            <div class="summary">
                                                       
                                <p class="intro"><?php echo Util::niceWordsByChars($item->intro, 50, '...'); ?></p>
                                <h3 class="price">
                                        <?php 
                                        if (isset($attributes[$item->id]['price']) && $attributes[$item->id]['price'] != '0'):
                                            if (is_numeric($attributes[$item->id]['price'])) :
                                                echo Util::formatMoney($attributes[$item->id]['price']). 'đ'; 
                                            else: 
                                                echo $attributes[$item->id]['price'];
                                            endif;
                                            echo '<sup>VND</sup>';
                                        else : 
                                            echo 'Liên hệ';
                                        endif;
                                        ?>
                                </h3>
                                <a href="<?php echo $this->url->get(array('for' => 'cart_add', 'query' => '?' . http_build_query(array('id' => $item->id)))); ?>" class="M-btn  btn-icon  btn-primary">
                                    <i class="fa fa-shopping-cart"></i><span>Đặt hàng</span>
                                </a>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                    </article>
                <?php endforeach; ?>
                <div class="clearfix"></div>
                <div class="pagenavi">
                    <?php if ($result->total_pages > 1): ?>
                        <div class="page-navi ajax">
                            <?php if ($result->before == $result->current): ?>
                                <a class="prev item active"><</a>
                            <?php else: ?>
                                <a href="<?php echo $this->url->get(array('for' => 'article_list', 'slug' => $category->slug, 'id' => $category->id, 'query' => '?' . http_build_query(array('page' => $result->before)))); ?>" class="prev item"><</a>
                            <?php endif; ?>

                            <?php if ($result->current == $result->last): ?>
                                <?php $start = $result->current - 4; ?>
                            <?php else: ?>
                                <?php $start = $result->current - 3; ?>
                            <?php endif; ?>

                            <?php for ($i = $start; $i < $result->current; $i++): ?>
                                <?php if ($i > 0): ?>
                                <a href="<?php echo $this->url->get(array('for' => 'article_list', 'slug' => $category->slug, 'id' => $category->id, 'query' => '?' . http_build_query(array('page' => $i)))); ?>" class="item">
                                        <?php echo $i; ?>
                                    </a>
                                <?php endif; ?>
                            <?php endfor; ?>

                            <a class="item active">
                                <?php echo $result->current; ?>
                            </a>

                            <?php if ($result->current == 1): ?>
                                <?php $end = $result->current + 4; ?>
                            <?php else: ?>
                                <?php $end = $result->current + 3; ?>
                            <?php endif; ?>

                            <?php for ($i = $result->current + 1; $i <= $end; $i++): ?>
                                <?php if ($i <= $result->last): ?>
                                <a href="<?php echo $this->url->get(array('for' => 'article_list', 'slug' => $category->slug, 'id' => $category->id, 'query' => '?' . http_build_query(array('page' => $i)))); ?>" class="item">
                                        <?php echo $i; ?>
                                    </a>
                                <?php endif; ?>
                            <?php endfor; ?>

                            <?php if ($result->next == $result->current): ?>
                                <a class="next item active">></a>
                            <?php else: ?>
                                <a href="<?php echo $this->url->get(array('for' => 'article_list', 'slug' => $category->slug, 'id' => $category->id, 'query' => '?' . http_build_query(array('page' => $result->next)))); ?>" class="next item">></a>
                            <?php endif; ?>
                        </div>
                    <?php endif; ?>
                </div>
            <?php else: ?>
                Thông tin đang cập nhật. Bạn có thể xem các thông tin khác hoặc quay lại sau.
            <?php endif; ?>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-sm-12 col-md-12 congso-main-content">
                <?php echo $product_newer_box_layout; ?>
            </div>
            <div class="col-sm-12 col-md-12 congso-main-content">
                <?php echo $most_viewed_box_layout; ?>
            </div>
        </div>
    </div>
</section>