<?php use ITECH\Datasource\Lib\Util; ?>
<div class="top-header">
    <div class="container text-center">
        <h1 class="title-post"><?php echo $article->title; ?></h1>
        <div class="breamcrum">
            <?php echo $this->partial($__theme . '/element/layout/_breadcrumbs'); ?>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class=" pull-right primary col-md-9 ">
            <div class="text-des">
                <?php echo $article_content->content; ?>
            </div>
            <div class="clearfix"></div>
            <div class="title-related">
                <h4 class="title">Sản phẩm liên quan</h4>
            </div>
            
            <div class="list-post-category">		
                <?php if($related): ?>
                    <?php foreach ($related as $item): ?>
                        <?php 
                            if (!$item->alias):
                                $item->alias = Util::slug($item->title); 
                            endif;
                        ?>
                        <div class="item">
                            <div class="entry">
                                <a href="<?php echo $this->url->get(array('for' => 'article_detail', 'id' => $item->id, 'slug' => $item->alias)); ?>" class="thumbnail-pro frame-th" data-ratio="1.67">
                                    <?php if ($item->image != ''): ?>
                                        <img src="<?php echo $this->config->asset->home_image_url . '250/' . $item->image; ?>" alt="<?php echo $item->title; ?>">
                                    <?php else: ?>
                                        <img src="<?php echo $this->config->asset->home_image_url . 'default.gif'; ?>" alt="<?php echo $item->title; ?>">
                                    <?php endif; ?>
                                </a>
                                <h3 class="title-post">
                                    <?php echo $item->title; ?>
                                </h3>
                                <div class="price">
                                    <span class="price-old">
                                        <?php if (isset($related_attributes[$item->id]['price'])): ?>
                                            <?php $price = Util::formatMoney($related_attributes[$item->id]['price']); ?>
                                            <?php if ($price == 0): ?>
                                                <?php echo $related_attributes[$item->id]['price']; ?>    
                                            <?php else: ?>
                                                <?php echo $price . 'đ'; ?>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </span>
                                    <span class="price-new">
                                        <?php if (isset($related_attributes[$item->id]['price'])): ?>
                                            <?php $price = Util::formatMoney($related_attributes[$item->id]['price']); ?>
                                            <?php if ($price == 0): ?>
                                                <?php echo $related_attributes[$item->id]['price']; ?>    
                                            <?php else: ?>
                                                <?php echo $price . 'đ'; ?>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </span>
                                </div>
                            </div>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>
            </div>
            <div class="clearfix"></div>
        </div>
       
    </div> 
</div>