<?php use ITECH\Datasource\Lib\Util; ?>

<?php if($result && count($result) > 0): ?>
    <div class="congso-aside-block">
        <h2 class="aside-title"><?php echo $category->name; ?></h2>
        <div class="aside-post">
            <?php foreach($result as $item): ?>
                <div class="congso-post-block">
                    <div class="post-image">
                        <?php if ($item->image != ''): ?>
                            <img src="<?php echo $this->config->asset->home_image_url . '150/' . $item->image; ?>" alt="<?php echo $item->title; ?>">
                        <?php else: ?>
                            <?php if ($item->image == ''): ?>
                                <img src="<?php echo $this->config->asset->home_image_url . 'image_not_found.jpg'; ?>" alt="<?php echo $item->title; ?>">
                            <?php endif; ?>
                        <?php endif; ?>
                    </div>
                    <div class="post-detail">
                        <h2 class="post-title"><a href="<?php echo $this->url->get(array('for' => 'article_detail','id' => $item->id, 'slug' => $item->alias)); ?>" class="title-post"><?php echo util::niceWordsByChars($item->title,90); ?></a></h2>
                    </div>
                </div>
            <?php endforeach;?>
        </div>
    </div>
<?php endif; ?>