<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title><?php echo $title_for_layout; ?></title>

        <meta name="description" content="">
        <meta name="keywords" content="">
        <meta name="robots" content="index, follow">

        <link type="image/x-icon" rel="shortcut icon" href="<?php echo $this->config->asset->admin_image_url . 'favicon.png'; ?>">
        <link type="image/x-icon" rel="icon" href="<?php echo $this->config->asset->admin_image_url . 'favicon.png'; ?>">
        <link rel="image_src" href="<?php echo $this->config->asset->home_image_url . 'logo.png'; ?>">

        <?php echo $this->partial($__theme. '/element/layout/_asset'); ?>
    </head>
    <body>
        <?php echo $this->partial($__theme. '/element/layout/_header'); ?>
        <?php echo $this->getContent(); ?>
        <div id="fb-root"></div>
        <?php echo $this->partial('default/element/layout/_script'); ?>
        <?php echo $this->partial('default/element/layout/_bottom_asset'); ?>
        <!-- <?php echo round(microtime(true) - START_TIME, 3) . 's'; ?> -->
    </body>
</html>