<!DOCTYPE html>
<!--[if IE 8]><html class="ie8 no-js" lang="en"><![endif]-->
<!--[if IE 9]><html class="ie9 no-js" lang="en"><![endif]-->
<!--[if !IE]><!-->
<html lang="en" class="no-js">
<!--<![endif]-->
    <head>
        <title>Administrator - Developed by VinaDesign</title>
        <meta charset="utf-8">
        <!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge,IE=9,IE=8,chrome=1"><![endif]-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">
        <meta name="apple-mobile-web-app-capable" content="yes">
        <meta name="apple-mobile-web-app-status-bar-style" content="black">

        <meta name="description" content="">
        <meta name="keywords" content="">
        <meta name="robots" content="noindex, nofollow">

        <link rel="shortcut icon" href="<?php echo $this->config->asset->admin_image_url . 'favicon.ico'; ?>">
        <link type="text/css" rel="stylesheet" href="<?php echo $this->config->asset->admin_plugin_url . 'bootstrap/css/bootstrap.min.css?' . $this->config->asset->version; ?>">
        <link type="text/css" rel="stylesheet" href="<?php echo $this->config->asset->admin_plugin_url . 'font-awesome/css/font-awesome.min.css?' . $this->config->asset->version; ?>">
        <link type="text/css" rel="stylesheet" href="<?php echo $this->config->asset->admin_font_url . 'style.css?' . $this->config->asset->version; ?>">
        <link type="text/css" rel="stylesheet" href="<?php echo $this->config->asset->admin_css_url . 'main.css?' . $this->config->asset->version; ?>">
        <link type="text/css" rel="stylesheet" href="<?php echo $this->config->asset->admin_css_url . 'main-responsive.css?' . $this->config->asset->version; ?>">
        <link type="text/css" rel="stylesheet" href="<?php echo $this->config->asset->admin_plugin_url . 'iCheck/skins/all.css?' . $this->config->asset->version; ?>">
        <link type="text/css" rel="stylesheet" href="<?php echo $this->config->asset->admin_plugin_url . 'bootstrap-colorpalette/css/bootstrap-colorpalette.css?' . $this->config->asset->version; ?>">
        <link type="text/css" rel="stylesheet" href="<?php echo $this->config->asset->admin_plugin_url . 'perfect-scrollbar/src/perfect-scrollbar.css?' . $this->config->asset->version; ?>">
        <link type="text/css" rel="stylesheet" href="<?php echo $this->config->asset->admin_css_url . 'theme_light.css?' . $this->config->asset->version; ?>" id="skin_color">
        <link type="text/css" rel="stylesheet" href="<?php echo $this->config->asset->admin_css_url . 'print.css?' . $this->config->asset->version; ?>" media="print">
        <link type="text/css" rel="stylesheet" href="<?php echo $this->config->asset->admin_plugin_url . 'DataTables/media/css/DT_bootstrap.css?' . $this->config->asset->version; ?>">
        <link type="text/css" rel="stylesheet" href="<?php echo $this->config->asset->admin_plugin_url . 'datepicker/css/datepicker.css?' . $this->config->asset->version; ?>">
        <link type="text/css" rel="stylesheet" href="<?php echo $this->config->asset->admin_plugin_url . 'select2/select2.css?' . $this->config->asset->version; ?>">
        <link type="text/css" rel="stylesheet" href="<?php echo $this->config->asset->admin_plugin_url . 'jQuery-Tags-Input/jquery.tagsinput.css?' . $this->config->asset->version; ?>">
        <link type="text/css" rel="stylesheet" href="<?php echo $this->config->asset->admin_plugin_url . 'bootstrap-fileupload/bootstrap-fileupload.min.css?' . $this->config->asset->version; ?>">
        <link type="text/css" rel="stylesheet" href="<?php echo $this->config->asset->admin_plugin_url . 'dropzone/downloads/css/dropzone.css?' . $this->config->asset->version; ?>">
        <link type="text/css" rel="stylesheet" href="<?php echo $this->config->asset->admin_plugin_url . 'bootstrap-modal/css/bootstrap-modal-bs3patch.css?' . $this->config->asset->version; ?>">
        <link type="text/css" rel="stylesheet" href="<?php echo $this->config->asset->admin_plugin_url . 'bootstrap-modal/css/bootstrap-modal.css?' . $this->config->asset->version; ?>">
        <!--[if lt IE 9]>
            <script type="text/javascript" src="<?php echo $this->config->asset->admin_plugin_url . 'respond.min.js?' . $this->config->asset->version; ?>"></script>
            <script type="text/javascript" src="<?php echo $this->config->asset->admin_plugin_url . 'excanvas.min.js?' . $this->config->asset->version; ?>"></script>
            <script type="text/javascript" src="<?php echo $this->config->asset->admin_js_url . 'jquery.js?' . $this->config->asset->version; ?>"></script>
        <![endif]-->
        <!--[if gte IE 9]><!-->
            <script type="text/javascript" src="<?php echo $this->config->asset->admin_js_url . 'jquery.js?' . $this->config->asset->version; ?>"></script>
        <!--<![endif]-->
    </head>
    <body>
        <div class="main-container">
            <?php echo $this->getContent(); ?>
        </div>
        <script type="text/javascript" src="<?php echo $this->config->asset->admin_plugin_url . 'jquery-ui/jquery-ui-1.10.2.custom.min.js?' . $this->config->asset->version; ?>"></script>
        <script type="text/javascript" src="<?php echo $this->config->asset->admin_plugin_url . 'bootstrap/js/bootstrap.min.js?' . $this->config->asset->version; ?>"></script>
        <script type="text/javascript" src="<?php echo $this->config->asset->admin_plugin_url . 'bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js?' . $this->config->asset->version; ?>"></script>
        <script type="text/javascript" src="<?php echo $this->config->asset->admin_plugin_url . 'blockUI/jquery.blockUI.js?' . $this->config->asset->version; ?>"></script>
        <script type="text/javascript" src="<?php echo $this->config->asset->admin_plugin_url . 'iCheck/jquery.icheck.min.js?' . $this->config->asset->version; ?>"></script>
        <script type="text/javascript" src="<?php echo $this->config->asset->admin_plugin_url . 'perfect-scrollbar/src/jquery.mousewheel.js?' . $this->config->asset->version; ?>"></script>
        <script type="text/javascript" src="<?php echo $this->config->asset->admin_plugin_url . 'perfect-scrollbar/src/perfect-scrollbar.js?' . $this->config->asset->version; ?>"></script>
        <script type="text/javascript" src="<?php echo $this->config->asset->admin_plugin_url . 'less/less-1.5.0.min.js?' . $this->config->asset->version; ?>"></script>
        <script type="text/javascript" src="<?php echo $this->config->asset->admin_plugin_url . 'jquery-cookie/jquery.cookie.js?' . $this->config->asset->version; ?>"></script>
        <script type="text/javascript" src="<?php echo $this->config->asset->admin_plugin_url . 'bootstrap-colorpalette/js/bootstrap-colorpalette.js?' . $this->config->asset->version; ?>"></script>
        <script type="text/javascript" src="<?php echo $this->config->asset->admin_js_url . 'main.js?' . $this->config->asset->version; ?>"></script>
        <script type="text/javascript" src="<?php echo $this->config->asset->admin_plugin_url . 'bootstrap-datepicker/js/bootstrap-datepicker.js?' . $this->config->asset->version; ?>"></script>
        <script type="text/javascript" src="<?php echo $this->config->asset->admin_plugin_url . 'select2/select2.min.js?' . $this->config->asset->version; ?>"></script>
        <script type="text/javascript" src="<?php echo $this->config->asset->admin_plugin_url . 'select2/select2_locale_vi.js?' . $this->config->asset->version; ?>"></script>
        <script type="text/javascript" src="<?php echo $this->config->asset->admin_plugin_url . 'jQuery-Tags-Input/jquery.tagsinput.js?' . $this->config->asset->version; ?>"></script>
        <script type="text/javascript" src="<?php echo $this->config->asset->admin_plugin_url . 'ckeditor/ckeditor.js?' . $this->config->asset->version; ?>"></script>
        <script type="text/javascript" src="<?php echo $this->config->asset->admin_plugin_url . 'ckeditor/adapters/jquery.js?' . $this->config->asset->version; ?>"></script>
        <script type="text/javascript" src="<?php echo $this->config->asset->admin_plugin_url . 'bootstrap-fileupload/bootstrap-fileupload.min.js?' . $this->config->asset->version; ?>"></script>
        <script type="text/javascript" src="<?php echo $this->config->asset->admin_plugin_url . 'nestable/jquery.nestable.js?' . $this->config->asset->version; ?>"></script>
        <script type="text/javascript" src="<?php echo $this->config->asset->admin_js_url . 'ui-nestable.js?' . $this->config->asset->version; ?>"></script>
        <script type="text/javascript" src="<?php echo $this->config->asset->admin_plugin_url . 'bootstrap-modal/js/bootstrap-modal.js?' . $this->config->asset->version; ?>"></script>
        <script type="text/javascript" src="<?php echo $this->config->asset->admin_plugin_url . 'bootstrap-modal/js/bootstrap-modalmanager.js?' . $this->config->asset->version; ?>"></script>
        <script type="text/javascript" src="<?php echo $this->config->asset->admin_plugin_url . 'tinymce/tinymce.min.js?' . $this->config->asset->version; ?>"></script>
        <script type="text/javascript" src="<?php echo $this->config->asset->admin_js_url . 'ui-modals.js?' . $this->config->asset->version; ?>"></script>
        <script type="text/javascript" type="text/javascript">
            $(document).ready(function() {
                Main.init();
                UINestable.init();
                UIModals.init();

                $('.date-picker').datepicker({
                    autoclose: true,
                    format: 'dd-mm-yyyy'
                });

                $('.search-select').select2({
                    allowClear: true,
                    maximumSelectionSize: 3
                });
                
               // CKEDITOR.disableAutoInline = true;
              //  $('.ckeditor').ckeditor({
               //     height: '300px',
               //     filebrowserBrowseUrl : '<?php echo $this->url->get(array('for' => 'article_list_image')); ?>',
               //     filebrowserImageBrowseUrl : '<?php echo $this->url->get(array('for' => 'article_list_image')); ?>',
                //    filebrowserFlashBrowseUrl : '<?php echo $this->url->get(array('for' => 'article_list_image')); ?>',
                //    filebrowserUploadUrl: '<?php echo $this->url->get(array('for' => 'article_list_image')); ?>'
               // });
                
                $('.nestable').each(function(){
                    var $nestable = $(this);
                    $nestable.nestable({
                    })
                        .on('change', function(e) {
                                return $.post($nestable.attr('data-url'), {links:$nestable.nestable('serialize')});
                            })
                        .on('mouseenter mouseleave', 'div.dd3-content', function(event){
                            var $task = $(this).find('.btn-task-group').stop(true,true);
                            if(event.type == 'mouseenter'){
                                $task.css('visibility', 'visible');  
                            } else {
                                $task.css('visibility', 'hidden');  
                            }
                            return false;
                    });
                });
                
                $('#nestable3').nestable();
                $('#tag-string').tagsInput({width:'auto'});
            });
                
        </script>
        <script type="text/javascript">
        tinyMCE.init({
                selector: "textarea.editor",
                plugins : "link,autolink,lists,spellchecker,pagebreak,layer,table,save,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,template,image",
                theme_advanced_buttons1 : "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect,formatselect,fontselect,fontsizeselect",
                theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
                theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
                theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,spellchecker,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,blockquote,pagebreak,|,insertfile,insertimage",
                theme_advanced_toolbar_location : "top",
                theme_advanced_toolbar_align : "left",
                theme_advanced_statusbar_location : "bottom",
                theme_advanced_resizing : true,
                height : 350
                
        });
        </script>
        <!-- <?php echo round(microtime(true) - START_TIME, 3) . 's'; ?> -->
    </body>
</html>