<div class="block-widget">
    <div class="header-widget">
        <h3 class="title">Hỗ trợ trực tuyến</h3>
    </div>
    <div class="content-widget">
        <div class="list-httt">
            <ul class="menu-horizon-tuvan">
                <li style="text-align: center;">
                    <span class="c"><a href="ymsgr:sendim?dung_sangomanhtri">
                            <img src="<?php echo $this->config->asset->home_image_url . 'online.gif'; ?>" alt="Dung Sàn gỗ" title="Dung Sàn gỗ">
                        </a>
                    </span>
                </li>
                <li align="center" style="text-align: center;" class="c">Kinh Doanh<br> (08) 3960 0785 </li>
                <li style="text-align: center;"><span class="c"><a href="ymsgr:sendim?tuyet_sangomanhtri"><img src="<?php echo $this->config->asset->home_image_url . 'online.gif'; ?>" alt="Tuyết Sàn gỗ" title="Tuyết Sàn gỗ"></a></span></li>
                <li style="text-align: center;" class="c">Kinh Doanh<br>(08) 3969 8283</li>
                <li style="text-align: center;"><span class="c"><a href="ymsgr:sendim?sango_hcm"><img src="<?php echo $this->config->asset->home_image_url . 'online.gif'; ?>" alt="Sàn gỗ HCM" title="Sàn gỗ HCM"></a></span></li>
                <li style="text-align: center;" class="c">Thi công - Kỹ thuật<br>0912.991.633</li>
                <li style="text-align: center;"><span class="c"><a href="ymsgr:sendim?thanh_sangomanhtri"><img src="<?php echo $this->config->asset->home_image_url . 'online.gif'; ?>" alt="Thi công sàn gỗ" title="Thi công sàn gỗ"></a></span></li>
                <li style="text-align: center;" class="c">Than phiền chất lượng DV<br> 0908.727.785</li>
                <li style="text-align: center;"><span class="c"><a href="ymsgr:sendim?sangotphcm"><img src="<?php echo $this->config->asset->home_image_url . 'online.gif'; ?>" alt="Sàn gỗ HCM" title="Sàn gỗ HCM"></a></span></li>
                <li style="text-align: center;" class="c">Chăm sóc khách hàng<br> (08) 2213 2162 </li>
                <center><span class="c"><a href="skype:sangomanhtri?chat"><img src="<?php echo $this->config->asset->home_image_url . 'skype_logo.gif'; ?>" alt="Chat with me" height="52" width="160"></a> </span></center>
                <li align="center" style="text-align: center;" class="c">Tư vấn 24/7 - Mr Trí<br> 0913.03.03.03</li>
            </ul>
        </div>
    </div>
</div>