<?php use ITECH\Datasource\Lib\Util; ?>
<?php use ITECH\Datasource\Lib\Constant; ?>

<?php $select_type = Constant::articleTypeSelect(); ?>
<section id="section2">
    <div class="container">
        <div class="row">
            <?php echo $this->partial($__theme. '/element/layout/_breadcrumbs', array('breadcrumbs' => $breadcrumbs)); ?>
            <div class="col-lg-8 col-md-8 congso-main-content">
            <?php if($result->total_items > 0): ?>
                <div class="congso-list-post">.
                    <?php foreach($result->items as $item): ?>
                    <div class="congso-post-block">
                        <div class="post-image list-img">
                            <?php if ($item->image != ''): ?>
                                <img src="<?php echo $this->config->asset->home_image_url . '250/' . $item->image; ?>" alt="<?php echo $item->title; ?>">
                            <?php else: ?>
                                <?php if ($item->image == ''): ?>
                                    <img src="<?php echo $this->config->asset->home_image_url . 'image_not_found.jpg'; ?>" alt="<?php echo $item->title; ?>">
                                <?php endif; ?>
                            <?php endif; ?>
                        </div>
                        <div class="post-detail list-category">
                            <h2 class="post-title">
                                <?php if ($item->type == Constant::ARTICLES_FOCUS || $item->type == Constant::ARTICLES_FOCUS || $item->type == Constant::ARTICLES_NEW): ?>
                                    <span class="congso-light">
                                        <?php echo $select_type[$item->type]; ?>
                                    </span>
                                <?php endif; ?>
                                <a href="<?php echo $this->url->get(array('for' => 'article_detail','id' => $item->id, 'slug' => $item->alias)); ?>" class="title-post"><?php echo $item->title; ?></a></h2>
                            <div class="post-author">
                                <a class="author-name" href="">
                                    <b style="color: red"><?php echo $item->admin_name; ?></b>, <?php echo Constant::MEMBER; ?>
                                </a>
                            </div>
                            <div class="post-body">
                                <?php echo util::cutTextByChars($item->intro,250); ?>
                            </div>
                            <div class="post-footer">
                                <a href="<?php echo $this->url->get(array('for' => 'article_detail','id' => $item->id, 'slug' => $item->alias)); ?>" class="congso-readmore">
                                    Đọc tiếp <i class="fa fa-share"></i>
                                </a>
                                <div class="congso-likebox">
                                    <div class="fb-like" data-href="<?php echo $this->url->get(array('for' => 'article_detail','id' => $item->id, 'slug' => $item->alias)); ?>" data-layout="button_count" data-action="like" data-show-faces="false" data-share="true"></div>
                                </div>

                                <span class="btn btn btn-default pull-right" style="padding: 0px 8px !important; margin-right: 4px; font-size:13px">
                                    <?php echo $item->hits . ' lượt xem'; ?>
                                </span>
                            </div>
                        </div>
                    </div>
                    <?php endforeach;?>

                    <div class="paging">
                        <?php if ($result->total_pages > 1): ?>
                            <div class="page-navi">
                                <?php if ($result->before == $result->current): ?>
                                    <a class="prev item active"><i class="fa fa-angle-left"></i></a>
                                <?php else: ?>
                                    <a href="<?php echo $this->url->get(array('for' => 'article_list', 'slug' => $category->slug, 'id' => $category->id, 'query' => '?' . http_build_query(array('page' => $result->before)))); ?>" class="prev item"><i class="fa fa-angle-left"></i></a>
                                <?php endif; ?>

                                <?php if ($result->current == $result->last): ?>
                                    <?php $start = $result->current - 4; ?>
                                <?php else: ?>
                                    <?php $start = $result->current - 3; ?>
                                <?php endif; ?>

                                <?php for ($i = $start; $i < $result->current; $i++): ?>
                                    <?php if ($i > 0): ?>
                                    <a href="<?php echo $this->url->get(array('for' => 'article_list', 'slug' => $category->slug, 'id' => $category->id, 'query' => '?' . http_build_query(array('page' => $i)))); ?>" class="item">
                                            <?php echo $i; ?>
                                        </a>
                                    <?php endif; ?>
                                <?php endfor; ?>

                                <a class="item active">
                                    <?php echo $result->current; ?>
                                </a>

                                <?php if ($result->current == 1): ?>
                                    <?php $end = $result->current + 4; ?>
                                <?php else: ?>
                                    <?php $end = $result->current + 3; ?>
                                <?php endif; ?>

                                <?php for ($i = $result->current + 1; $i <= $end; $i++): ?>
                                    <?php if ($i <= $result->last): ?>
                                    <a href="<?php echo $this->url->get(array('for' => 'article_list', 'slug' => $category->slug, 'id' => $category->id, 'query' => '?' . http_build_query(array('page' => $i)))); ?>" class="item">
                                            <?php echo $i; ?>
                                        </a>
                                    <?php endif; ?>
                                <?php endfor; ?>

                                <?php if ($result->next == $result->current): ?>
                                    <a class="next item active"><i class="fa fa-angle-right"></i></a>
                                <?php else: ?>
                                    <a href="<?php echo $this->url->get(array('for' => 'article_list', 'slug' => $category->slug, 'id' => $category->id, 'query' => '?' . http_build_query(array('page' => $result->next)))); ?>" class="next item">
                                        <i class="fa fa-angle-right"></i>
                                    </a>
                                <?php endif; ?>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>
            <?php else:?>
                Thông tin đang cập nhật
            <?php endif;?>
            </div>
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="congso-aside-block">
                    <h2 class="aside-title">Tin mới nhất</h2>
                    <?php echo $most_new_layout; ?>
                </div>

                <div class="clearfix"></div>
                <?php if(!$category->category_h2=='' && !$category->category_content_2 ==''){?>
                <div class="congso-aside-block" style="border: #d7d7d7 solid 1px;border-radius: 6px;margin-bottom: 30px;line-height: 1.3;">
                     <h2 style="font-size: 15px;max-width:280px;font-weight:bold;margin-top: 10px;margin-left:10px;"><?php echo $category->category_h2;?></h2>
                        <div style="font: 13px; max-width: 280px;margin-left:10px;"><?php echo Util::htmlDecode($category->category_content_2);?></div>
                </div>
                <?php } ?>
                <?php if(!$category->category_h3=='' && !$category->category_content_3 ==''){?>
                <div class="clearfix"></div>

                 <div class="congso-aside-block" style="border: #d7d7d7 solid 1px;border-radius: 6px;margin-bottom: 30px;    line-height: 1.3;">
                    <h3 style="font-size: 15px;max-width:280px;font-weight:bold;margin-top: 10px;margin-left:10px;"><?php echo $category->category_h3;?></h3>
                    <div style="font: 13px; max-width: 290px;margin-left:10px;"><?php echo Util::htmlDecode($category->category_content_3);?></div>
                </div>
                <?php } ?>
            </div>
            <?php if (isset($listPostApi)): ?>
            <?php echo $listPostApi ? $listPostApi : '' ?>
            <?php endif; ?>
            <section id="section1">
                <div class="container">
                    <div class="row congso-list-main-post">
                        <div class="col-lg-12 col-md-12">
                            <h2 class="fresh-title">Tin nổi bật</h2>
                        </div>
                        <?php echo $fresh_layout; ?>
                    </div>
                </div>
            </section>
            <div class="col-lg-4 col-md-4 congso-main-aside">
                <?php if (isset($categories) && count($categories) > 0): ?>
                    <?php foreach ($categories as $item): ?>
                        <?php if ($item->id != $category->id): ?>
                            <div class="">
                                <div class="box-category box-category-slidebar">
                                    <?php if(isset($box_layout[$item->id])): ?>
                                    <?php echo $box_layout[$item->id]; ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <div class="clearfix"></div>
                        <?php endif; ?>
                    <?php endforeach; ?>
                <?php endif; ?>
            </div>
        </div>
    </div>    
</section>