<div class="container">
    <?php echo $this->partial('element/layout/_breadcrumbs'); ?>

    <form action="" method="POST" enctype="multipart/form-data" class="form-horizontal" role="form">
        <?php echo $this->flashSession->output(); ?>

        <div class="form-group">
            <label class="col-sm-2 control-label">
                Mật khẩu cũ
            </label>
            <div class="col-sm-9">
                <?php echo $form->render('old_password', array('class' => 'form-control')); ?>
                <?php echo $this->partial('element/layout/_message', array('form' => $form, 'element' => 'old_password')); ?>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">
                Mật khẩu mới
            </label>
            <div class="col-sm-9">
                <?php echo $form->render('new_password', array('class' => 'form-control')); ?>
                <?php echo $this->partial('element/layout/_message', array('form' => $form, 'element' => 'new_password')); ?>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">
                Nhập lại mật khẩu
            </label>
            <div class="col-sm-9">
                <?php echo $form->render('confirm_password', array('class' => 'form-control')); ?>
                <?php echo $this->partial('element/layout/_message', array('form' => $form, 'element' => 'confirm_password')); ?>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label"></label>
            <div class="col-sm-9">
                <button type="submit" id="button-update" class="btn btn-bricky">
                    Cập nhật
                </button>
                <a href="<?php echo $this->url->get(array('for' => 'profile')); ?>" class="btn btn-primary">
                    Trở lại
                </a>
            </div>
        </div>

        <input type="hidden" name="<?php echo $this->security->getTokenKey(); ?>" value="<?php echo $this->security->getToken(); ?>">
    </form>
</div>