<div class="container">
    <div class="col-xs-8 primary">
        <div class="inner-10">
            <div class="box-content ">
                <header class="block-title">
                    <h3 class="title font-roboto text-primary">
                        <span class="text">Quên mật khẩu</span>
                        <span class="line"></span>
                        <div class="pull-right">
                            <div class="hottline">
                                ĐT Hỗ trợ <b class="red">1900 6118</b>
                            </div>
                        </div>
                    </h3>
                </header>

                <div class="entry">
                    <ul class="no-style">
                        <li>
                            <span class="icon icon-arrow icon-xs"></span>
                            Thông tin hướng dẫn tạo mật khẩu mới đã được gửi đến email của bạn. Vui lòng kiểm tra email và làm theo hướng dẫn.
                        </li>
                        <li>
                            <span class="icon icon-arrow icon-xs"></span>
                            Nếu bạn có thắc mắc xin liên hệ hotline hỗ trợ:
                            Miền Bắc: <b class="red">(04) 7309 2828</b>
                            -
                            Miền Nam: <b class="red">(08) 7309 2828</b>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="sidebar col-xs-4">
        <div class="inner-10">
            <?php echo $this->partial('default/element/home/_subscriber'); ?>
            <?php echo $this->partial('default/element/home/_fb_like_box'); ?>
        </div>
    </div>

    <div class="clearfix"></div>
</div>