<link type="text/css" rel="stylesheet" href="<?php echo $this->config->asset->home_css_url . 'muabannhanhapi.css?'. $this->config->asset->version; ?>">
<?php use ITECH\Datasource\Lib\Util; ?>
<div class="container">
<?php if (isset($article) > 0 && count($article['result'])) : ?>
    <h1 class="post-title">
        <?php echo $user->name ? $user->name : '' ?>
    </h1>
    <div class="list-post block-category-mbn">
        <div class="list-wrap">
            <?php

            foreach ($article['result'] as $key => $item) {

                if (isset($item) && $item) :
                    $item = $item['_source'];
                    $url = $this->url->get(array('for'=>'mbn_detail','id'=>$item['id'],'mbnver'=>str_replace('-','',$item['category']['slug']),'slug'=>$item['slug']));
                    $name           = $item['name'] ? Util::niceWordsByChars($item['name'],45) : "";
                    $thumbnail      = $item['default_thumbnail_url'] ? $item['default_thumbnail_url'] : "";
                    $price          = $item['price'] ? number_format($item['price'],0,".",".").'<sup>VND</sup>' : "Liên hệ" ;
                    $type           = $item['type_value'] == 1 ? "Cần bán/ Dịch vụ" : "Cần mua/ Cần tìm" ;
                    $conditions     = $item['conditions'] ? $item['conditions'] : "";
                    $local          = $item['province']['name'] ? $item['province']['name'] : "";
                    $phone          = $item['user']['phone'] ? $item['user']['phone'] : "";
                    $updated        = $item['updated_at'];
                    $user_name      = $item['user']['name'];
                    $type_user      = $item['user']['membership_value'] == 23 ? '<span class="label-premium Partner">Partner</span>' :  $item['user']['membership_value'] == 22 ? '<span class="label-premium">Vip</span>' : '';
                    $category_id    = $item['category']['id'];
                    ?>
                    
                    <li class="item">
                        <div class="entry-item">
                            <a href="<?php echo $url; ?>">
                                <div class="info-left">
                                        <span class="thumbnail fix-frame" data-ratio="1.333">
                                            <img src="<?php echo $thumbnail; ?>" height="398" width="600" alt="<?php echo $name; ?>">
                                        </span>
                                </div>
                                <div class="summary">
                                    <div class="block-info">
                                        <h2 class="title">
                    <?php if($item['user']['membership_value']==23){
                    echo '<span class="label-premium Partner">Partner</span>';
                    }elseif($item['user']['membership_value']==22){
                        echo '<span class="label-premium">Vip</span>';
                    }else{
                        echo '';
                }?><?php echo $name; ?></h2>

                                        <p>
                                            <span class="fa fa-tags"></span>
                                            <span class="text"><?php echo $type ?></span>
                                        </p>

                                        <p>
                                            <span class="fa fa-info-circle"></span>
                                            <span class="text" itemprop="itemCondition"><?php echo $conditions ?></span>
                                        </p>

                                        <div class="clearfix"></div>

                                        <p>
                                            <span class="fa fa-map-marker"></span>
                                            <span class="text"><?php echo $local ?></span>
                                        </p>

                                        <p class="telephone-number">
                                            <span class="fa fa-phone"></span>
                                            <b class="text"><?php echo $phone ?></b>
                                        </p>

                                        <div class="clearfix"></div>
                                        <div class="price">
                                                                <span>
                                                                    <?php echo $price ?>
                                                                </span>
                                        </div>
                                    </div>
                                </div>
                                <div class="clearfix"></div>
                                <div class="post-meta">
                                    <div class="author-post"><h3 style="font-size: 10px;"><?php echo $user_name ?></h3></div>
                                    <div class="date-update">Cập nhật: <?php echo $updated ?></div>
                                </div>
                            </a>
                        </div>
                    </li>
                    
                <?php endif;
            }
            ?>
        </div>
    </div>
    <?php echo $pagination ? $pagination : ''; ?>
<?php else: ?>
    <div class="">
        <div class="alert alert-danger">
            Không tìm thấy tin đăng
            <a href="<?php echo $this->url->get(array('for' => 'mbn_home')); ?>" class="btn btn-success">Xem tin khác</a>
        </div>
    </div>
<?php endif; ?>

</div>
