<?php use ITECH\Datasource\Lib\Constant;?>
<section id="section1">
    <div class="container">
        <div class="text1">
            <b style="color: blue">Đường dẫn bạn vừa truy cập không tồn tại</b>
        </div>
        <div class="text2">
            <h1 class="home-h1"><?php echo Constant::SEO_WEB_SITE_DESCRIPTION.' ';?><a href="<?php echo $this->url->get(array('for' => 'home')); ?>"><?php echo Constant::SEO_WEB_SITE;?></a></h1>
        </div>
        <br><br>
        <div class="text2">
            Mời bạn truy cập:
        </div>
        <a href="<?php echo $this->url->get(array('for' => 'home')); ?>" title="">
            Trang chủ
        </a>
        <br><br>
        <div class="col-lg-12 col-md-12 congso-main-content col-0">
            <div class="row congso-list-sub-block">
                <?php if ($categories && count($categories) > 0): ?>
                    <?php $i = 1 ; ?>
                    <?php foreach ($categories as $item): ?>
                        <div class="col-lg-4 col-md-4 col-sm-4 box-home">
                            <div class="congso-sub-block box-detail">
                                <?php if(isset($box_layout[$item->id])): ?>
                                <?php echo $box_layout[$item->id]; ?>
                                <?php endif; ?>
                            </div>
                        </div>
                        <?php if ($i % 3 == 0): ?>
                            <div class="clearfix"></div>
                        <?php endif; ?>
                        <?php $i ++ ; ?>
                    <?php endforeach; ?>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
</div>