<link type="text/css" rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto+Slab:400,700,300&subset=vietnamese,latin">
<link type="text/css" rel="stylesheet" href="<?php echo $this->config->asset->home_plugin_url . 'font-awesome/css/font-awesome.min.css?' . $this->config->asset->version; ?>">
<link type="text/css" rel="stylesheet" href="<?php echo $this->config->asset->home_plugin_url . 'select2/select2.css?' . $this->config->asset->version; ?>">
<link type="text/css" rel="stylesheet" href="<?php echo $this->config->asset->home_plugin_url . 'iCheck/skins/all.css?' . $this->config->asset->version; ?>">
<link type="text/css" rel="stylesheet" href="<?php echo $this->config->asset->home_plugin_url . 'Datepicker/css/BeatPicker.min.css?' . $this->config->asset->version; ?>">
<link type="text/css" rel="stylesheet" href="<?php echo $this->config->asset->home_css_url . 'layout.css?' . $this->config->asset->version; ?>">
<link type="text/css" rel="stylesheet" href="<?php echo $this->config->asset->home_css_url . 'style.css?' . $this->config->asset->version; ?>">

<script type="text/javascript" src="<?php echo $this->config->asset->home_js_url . 'min/jquery-1.9.1.min.js?' . $this->config->asset->version; ?>"></script>
<script type="text/javascript" src="<?php echo $this->config->asset->home_fixbug_url . 'js/html5shiv.js?' . $this->config->asset->version; ?>"></script>
<script type="text/javascript" src="<?php echo $this->config->asset->home_plugin_url . 'select2/min/select2.min.js?' . $this->config->asset->version; ?>"></script>
<script type="text/javascript" src="<?php echo $this->config->asset->home_plugin_url . 'iCheck/jquery.icheck.min.js?' . $this->config->asset->version; ?>"></script>
<script type="text/javascript" src="<?php echo $this->config->asset->home_plugin_url . 'number-format/jquery.number.min.js?' . $this->config->asset->version; ?>"></script>
<script type="text/javascript" src="<?php echo $this->config->asset->home_plugin_url . 'Datepicker/js/BeatPicker.min.js?' . $this->config->asset->version; ?>"></script>
<script type="text/javascript" src="<?php echo $this->config->asset->home_js_url . 'min/app_vina.min.js?' . $this->config->asset->version; ?>"></script>
<script type="text/javascript" src="<?php echo $this->config->asset->home_js_url . 'min/global.min.js?' . $this->config->asset->version; ?>"></script>