<div class="container">
    <div class="inner-10">
        <div class="col-xs-3 offset10">
            <a href="">
                <i class="fa fa-chevron-right"></i>
                Dịch vụ tìm việc
            </a>
            <a href="">
                <i class="fa fa-chevron-right"></i>
                Dịch vụ tuyển dụng
            </a>
        </div>
        <div class="col-xs-3 offset10 push-left-10">
            <a href="<?php echo $this->config->static->home_url . 'bai-viet/thoa-thuan-su-dung'; ?>" title="Điều khoản sử dụng">
                <i class="fa fa-chevron-right"></i>
                Điều khoản sử dụng
            </a>
            <a href="<?php echo $this->config->static->home_url . 'lien-he'; ?>" title="Liên hệ">
                <i class="fa fa-chevron-right"></i>
                Liên hệ
            </a>
        </div>
        <div class="col-xs-3 offset10 push-left-10">
            <a href="">
                <i class="fa fa-chevron-right"></i>
                Guide
            </a>
            <a href="">
                <i class="fa fa-chevron-right"></i>
                Sitemap
            </a>
        </div>
        <div class="col-xs-3 offset20 push-left-10">
            <a href="">
                <i class="fa fa-chevron-right"></i>
                Message notification
            </a>
            <a href="">
                <i class="fa fa-chevron-right"></i>
                Career advice
            </a>
        </div>
        <div class="clearfix"></div>
    </div>
</div>