<div class="container">
    <div class="inner-10">
        <ul class="menu-left pull-left menu">
            <li>
                <a href="<?php echo $this->config->static->home_url . 'nguoitimviec'; ?>" title="Người tìm việc">
                    Người tìm việc
                </a>
            </li>
            <li>
                <a href="<?php echo $this->config->static->home_url . 'nhatuyendung'; ?>" title="Nhà tuyển dụng">
                    Nhà tuyển dụng
                </a>
            </li>
            <li>
                <a href="<?php echo $this->config->static->home_url . 'viec-lam/tinh-thanh'; ?>" title="Việc làm theo tỉnh thành">
                    Việc làm theo tỉnh thành
                </a>
            </li>
            <li>
                <a href="<?php echo $this->config->static->home_url . 'rss'; ?>" title="RSS">
                    RSS
                </a>
            </li>
            <li>
                <a href="http://nghenghiep.timviecnhanh.com" title="Góc nghề nghiệp" target="_blank">
                    Góc nghề nghiệp
                </a>
            </li>
        </ul>
        <ul class="menu-right pull-right menu">
            <li>
                <a href="<?php echo $this->config->static->home_url; ?>" title="Trang chủ">
                    <i class="fa fa-home"></i>
                    Trang chủ
                </a>
            </li>
            <li>
                <a href="#" title="Về đầu trang">
                    <span class="icon icon-xs icon-back-top"></span>
                    Về đầu trang
                </a>
            </li>
        </ul>
        <div class="clearfix"></div>
    </div>
</div>