<link type="text/css" rel="stylesheet" href="<?php echo $this->config->asset->home_css_url . 'blog/bootstrap.css?' . $this->config->asset->version; ?>">
<link type="text/css" rel="stylesheet" href="<?php echo $this->config->asset->home_css_url . 'blog/owl.carousel.css?'. $this->config->asset->version; ?>">
<link type="text/css" rel="stylesheet" href="<?php echo $this->config->asset->home_css_url . 'blog/owl.theme.css?'. $this->config->asset->version; ?>">
<link type="text/css" rel="stylesheet" href="<?php echo $this->config->asset->home_css_url . 'blog/node.css?'. $this->config->asset->version; ?>">
<link type="text/css" rel="stylesheet" href="<?php echo $this->config->asset->home_css_url . 'blog/font-awesome.css?'. $this->config->asset->version; ?>">
<link type="text/css" rel="stylesheet" href="<?php echo $this->config->asset->home_css_url . 'blog/style.css?'. $this->config->asset->version; ?>">
<link type="text/css" rel="stylesheet" href="<?php echo $this->config->asset->home_css_url . 'muabannhanhapi.css?'. $this->config->asset->version; ?>">
<link type="text/css" rel="stylesheet" href="<?php echo $this->config->asset->home_css_url . 'ads_style.css?'. $this->config->asset->version; ?>">
<script type="text/javascript" src="<?php echo $this->config->asset->home_js_url . 'blog/jquery-1.9.1.js?'. $this->config->asset->version; ?>"></script>
<script type="text/javascript" src="<?php echo $this->config->asset->home_js_url . 'blog/owl.carousel.js?'. $this->config->asset->version; ?>"></script>
<script type="text/javascript" src="<?php echo $this->config->asset->home_js_url . 'blog/bootstrap.js?'. $this->config->asset->version; ?>"></script>
<script type="text/javascript" src="<?php echo $this->config->asset->home_js_url . 'blog/popup.js?'. $this->config->asset->version; ?>"></script>


