<?php use ITECH\Datasource\Lib\Util; ?>

<?php if($result): ?>
    <div class="content-block font-0">
        <?php $row = 0; ?>
        <?php foreach ($result as $item): ?>
        <?php if ($row < 1): ?>
        <div class="col-xs-4 col-no-padding col-left"> 
            <span class="box-item">
                <?php
                    if (!$item->alias):
                        $item->alias = Util::slug($item->title);
                    endif;
                ?>
                <a href="<?php echo $this->url->get(array('for' => 'article_detail','id' => $item->id, 'slug' => $item->alias)); ?>" title="<?php echo $item->title; ?>">
                    <?php $file_headers = @get_headers($this->config->asset->home_image_url . '500/' . $item->image); ?>
                    <?php if ($item->image != '' && $file_headers[0] != 'HTTP/1.1 404 Not Found'): ?>
                        <img class="thumbnail" src="<?php echo $this->config->asset->home_image_url . '500/' . $item->image; ?>" alt="<?php echo $item->title; ?>">
                    <?php else: ?>
                        <img class="thumbnail" src="<?php echo $this->config->asset->home_image_url . 'default.gif'; ?>" alt="<?php echo $item->title; ?>">
                    <?php endif; ?>
                    <h2 class="name-product"><?php echo $item->title; ?>
                        <span class="gia ">
                            <?php if (isset($attributes[$item->id]['price'])): ?>
                                <?php $price = Util::formatMoney($attributes[$item->id]['price']); ?>
                                <?php if ($price == 0): ?>
                                    <?php echo $attributes[$item->id]['price']; ?>    
                                <?php else: ?>
                                    <?php echo $price . 'đ'; ?>
                                <?php endif; ?>
                            <?php endif; ?>
                        </span>
                     <i class="fa fa-info-circle pull-right"></i>
                    </h2>
                </a>       
                <a href="<?php echo $this->url->get(array('for' => 'cart_add', 'query' => '?' . http_build_query(array('id' => $item->id)))); ?>" class="M-btn  btn-icon  btn-primary">
                    <i class="fa fa-shopping-cart"></i>
                    <span>Đặt hàng</span>
                </a>
                <div class="action-item-product">
                    <a href="https://www.facebook.com/sharer/sharer.php?u=<?php echo $this->url->get(array('for' => 'article_detail','id' => $item->id, 'slug' => $item->alias)); ?>" target="_blank" ta class="icon-facebook"><i class="fa fa-facebook"></i></a>
                    <a href="https://plus.google.com/share?url=<?php echo $this->url->get(array('for' => 'article_detail','id' => $item->id, 'slug' => $item->alias)); ?>" target="_blank" class="icon-you"><i class="fa fa-google-plus"></i> </a>
                    <a href="" class="icon-love"><i class="fa fa-heart-o"></i></a>
                </div>
            </span>
            <?php endif; ?>
            <?php $row++; ?>
            <?php endforeach; ?>
        </div>


        <div class="col-xs-8 col-no-padding col-right">
        <?php $row = 0; ?>
        <?php foreach ($result as $item): ?>
            <?php if ($row > 0): ?>
                <?php
                    if (!$item->alias):
                        $item->alias = Util::slug($item->title);
                    endif;
                ?>
                <span class="box-item">
                    <a href="<?php echo $this->url->get(array('for' => 'article_detail','id' => $item->id, 'slug' => $item->alias)); ?>" title="<?php echo $item->title; ?>">
                        <?php $file_headers = @get_headers($image_url . '250/' . $item->image); ?> 
                        <?php if ($item->image != '' && $file_headers[0] != 'HTTP/1.1 404 Not Found'): ?>
                            <img class="thumbnail" src="<?php echo $this->config->asset->home_image_url . '250/' . $item->image; ?>" alt="<?php echo $item->title; ?>">
                        <?php else: ?>
                            <img class="thumbnail" src="<?php echo $this->config->asset->home_image_url . '/default.gif'; ?>" alt="<?php echo $item->title; ?>">
                        <?php endif; ?>
                        <h2 class="name-product"><?php echo $item->title; ?>
                            <span class="gia ">
                                <?php if (isset($attributes[$item->id]['price'])): ?>
                                    <?php $price = Util::formatMoney($attributes[$item->id]['price']); ?>
                                    <?php if ($price == 0): ?>
                                        <?php echo $attributes[$item->id]['price']; ?>   
                                    <?php else: ?>
                                        <?php echo $price . 'đ'; ?>
                                    <?php endif; ?>
                                <?php endif; ?> 
                            </span>
                            <i class="fa fa-info-circle pull-right"></i>
                        </h2>
                    </a>
                    <a href="<?php echo $this->url->get(array('for' => 'cart_add', 'query' => '?' . http_build_query(array('id' => $item->id)))); ?>" class="M-btn  btn-icon  btn-primary">
                        <i class="fa fa-shopping-cart"></i><span>Đặt hàng</span>
                    </a>
                    <div class="action-item-product">
                        <a href="https://www.facebook.com/sharer/sharer.php?u=<?php echo $this->url->get(array('for' => 'article_detail','id' => $item->id, 'slug' => $item->alias)); ?>" target="_blank" ta class="icon-facebook"><i class="fa fa-facebook"></i></a> <!-- Thay linproduct = link muôn share  -->
                        <a href="https://plus.google.com/share?url=<?php echo $this->url->get(array('for' => 'article_detail','id' => $item->id, 'slug' => $item->alias)); ?>" target="_blank" class="icon-you"><i class="fa fa-google-plus"></i> </a>
                        <a href="" class="icon-love"><i class="fa fa-heart-o"></i></a>
                    </div>
                </span>
            <?php endif; ?>
        <?php $row++; ?>
        <?php endforeach; ?>
        </div>
    </div>
    <div class="clearfix"></div>
<?php endif; ?>