<div class="container">
    <div class="inner-10">
        <div class="col-xs-4 offset10">
            <a href="<?php echo $this->config->static->home_url . 'thong-bao/khuyen-mai.html'; ?>" title="Chương trình khuyến mãi 10 năm Tìm Việc Nhanh và ra mắt giao diện mới" target="_blank">
                <img src="<?php echo $this->config->asset->home_image_url . 'km_tvn.png'; ?>" alt="Tìm việc nhanh">
            </a>
        </div>
        <div class="col-xs-8 info-right offset20 push-left-10">
            <ul class="list-info">
                <li>- Tuyển dụng nhanh nhất vì có hàng ngàn website việc làm đăng lại tin tuyển dụng của TimViecNhanh.com</li>
                <li>- Nhãn hiệu nổi tiếng TimViecNhanh đã được bảo hộ độc quyền nhãn hiệu số 4-0150860-000</li>
                <li>- Giấy phép Mạng Xã Hội trực tuyến số 25-MXH của Bộ Thông Tin Truyền Thông</li>
                <li>- Giấy phép Trang Tin điện tử tổng hợp số 57/GP-ICP-STTTT của Sở Thông Tin Truyền Thông</li>
                <li>- Giấy chứng nhận đăng ký kinh doanh số: 0303452460 do Sở KHDT TP.Hồ Chí Minh cấp ngày 16/08/2004</li>
            </ul>
        </div>
        <div class="clearfix"></div>
    </div>
</div>