<div class="container">
    <div class="col-xs-8 primary">
        <div class="inner-10">
            <div class="box-content ">
                <header class="block-title">
                    <h3 class="title font-roboto text-primary">
                        <span class="text">Người tìm việc quên mật khẩu</span>
                        <span class="line"></span>
                        <div class="pull-right">
                            <div class="hottline">
                                ĐT Hỗ trợ <b class="red">1900 6118</b>
                            </div>
                        </div>
                    </h3>
                </header>

                <div class="entry">
                    <ul class="no-style">
                        <li>
                            <span class="icon icon-arrow icon-xs"></span>
                            Mời bạn nhập địa chỉ email đã đăng ký trên tài khoản TimViecNhanh.Com.
                        </li>
                        <li>
                            <span class="icon icon-arrow icon-xs"></span>
                            Tìm Việc Nhanh sẽ gửi tới bạn hướng dẫn để tạo mật khẩu mới, vui lòng kiểm tra email.
                        </li>
                    </ul>

                    <form action="" method="POST" enctype="multipart/form-data" class="form-employers-register">
                        <?php echo $this->flashSession->output(); ?>

                        <div class="group-field">
                            <label for="" class="label-form">
                                Email đăng ký <span class="icon icon-xs icon-hoa-thi"></span>
                            </label>
                            <?php echo $form->render('email'); ?>
                            <?php echo $this->partial('default/element/layout/_message', array('form' => $form, 'element' => 'email')); ?>
                        </div>
                        <div class="row-btn">
                            <div class="button-bottom">
                                <div class="col-xs-4 offset10 text-right">
                                    <button type="submit" class="btn btn-big btn-danger col-xs-2 col-push-2">
                                        Gửi email
                                    </button>
                                </div>
                            </div>
                            <div class="clearfix"></div>
                        </div>

                        <input type="hidden" name="<?php echo $this->security->getTokenKey(); ?>" value="<?php echo $this->security->getToken(); ?>">
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="sidebar col-xs-4">
        <div class="inner-10">
            <?php echo $this->partial('default/element/home/_subscriber'); ?>
            <?php echo $this->partial('default/element/home/_fb_like_box'); ?>
        </div>
    </div>

    <div class="clearfix"></div>
</div>