<?php
    $query = array(
        'page' => $page,
        'q' => $q,
        'cache_name' => $cache_name
    );
?>
<div class="container">
    <?php echo $this->partial('element/layout/_breadcrumbs'); ?>
    <?php echo $this->flashSession->output(); ?>
    <div class="text-right">
        <a class="btn btn-primary" href="<?php echo $this->url->get(array('for' => 'ad_position_add', 'query' => '?' . http_build_query($query))); ?>"> Thêm vị trí </a> 
    </div>
    <p></p>
    <?php echo $this->partial('ad/_list_position'); ?>
    <?php
    echo $this->partial('element/layout/_pagination', array(
        'result' => $result,
        'for' => 'position',
        'query' => array(
            'page' => $page,
            'q' => $q
        )
    ));
    ?>
</div>