<div class="container">
    <div class="inner-10">
        <div class="col-xs-4 logo-footer offset10">
            <a href="<?php echo $this->config->static->home_url; ?>" title="Tìm việc nhanh">
                <img src="<?php echo $this->config->asset->home_image_url . 'logomau.png'; ?>" alt="Tìm việc nhanh">
            </a>
        </div>
        <div class="col-xs-8 info-right  offset20 push-left-10">
            <div class="border-b-1">
                <h2 class="title text-primary" style="margin-top:3px;">Công ty Cổ Phần Tìm Việc Nhanh</h2>
                <p>
                    <b>Trụ sở: </b>Tầng 6, Bitexco Nam Long - 63A Võ Văn Tần, P.6, Q.3, TP.Hồ Chí Minh
                    <br>
                    <b>Điện thoại: </b>(08) 7309 8888 | <b>Fax: </b>(08) 393 018 00 | <b>Email: </b>lienhe@timviecnhanh.com
                </p>
                <p>
                    <b>Văn phòng đại diện: </b> Tầng 17, Tòa nhà Thăng Long, 98 Ngụy Như Kon Tum, Thanh Xuân, TP.Hà Nội
                    <br>
                    <b>Điện thoại: </b>(04) 7309 8888 | <b>Email: </b>hanoi@timviecnhanh.com
                </p>
                <p>
                    <b>Điện thoại hỗ trợ tại Đà Nẵng</b>: (0511) 7309 888
                </p>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>