<div class="container">
    <div class="menu-top">
        <a href="<?php echo $this->config->static->home_url . 'nguoitimviec'; ?>" class="menu-top-item" title="Người tìm việc">
            <i class="icon icon-sm icon-nguoi-tim-viec"></i>
            Người tìm việc
        </a>
        <a href="<?php echo $this->config->static->home_url . 'nhatuyendung'; ?>" class="menu-top-item" title="Nhà tuyển dụng">
            <i class="icon icon-sm icon-nha-tuyen-dung"></i>
            Nhà tuyển dụng
        </a>
        <a href="<?php echo $this->config->static->home_url . 'viec-lam/tinh-thanh'; ?>" class="menu-top-item" title="Việc làm theo tỉnh thành">
            <i class="icon icon-sm icon-viec-lam-theo-tinh-thanh"></i>
            Việc làm theo tỉnh thành
        </a>
        <a href="http://nghenghiep.timviecnhanh.com" class="menu-top-item" title="Góc nghề nghiệp" target="_blank">
            <i class="icon icon-sm icon-goc-nghe-nghiep"></i>
            Góc nghề nghiệp
        </a>

        <div class="addthis_toolbox addthis_default_style" addthis:url="https://www.facebook.com/timviecnhanh" style="width: 24%;">
            <a class="addthis_button_facebook_like" fb:like:layout="button"></a>
            <a class="addthis_button_google_plusone" g:plusone:count="false" g:plusone:size="medium"></a>
            <a class="addthis_native_toolbox"></a>
        </div>
    </div>
    <div class="clearfix"></div>
</div>