<?php use ITECH\Datasource\Lib\Util; ?>

<div class="col-md-4">
    <div class="block-head">
        <h3 class="title">Thông tin liên hệ</h3>
    </div>
    <div class="address">
        <div class="line">
                <span class="fa"></span> <b>Địa chỉ</b>: 46 Nguyen Chi Thanh(noi dai), P.16, Q.11, Ho Chi Minh
        </div>
        <div class="line">
                <span class="fa"></span> <b>Email</b>: info@manhtri.vn
        </div>
        <div class="line">
                <span class="fa"></span> <b>Tel</b>: (08) 3969 8382 - 3906 0785 - 2213 2162
        </div>
        <div class="line">
                <span class="fa"></span> <b>Facebook</b>: fanpage-link
        </div>
        <div class="time-w">
                <div><b>T2 - T6:</b> 9:30am - 6:30pm</div>
                <div><b>Thu 7: </b> 10:00am - 5:00pm </div>
                <div><b>CN: </b> Nghỉ </div>
        </div>
    </div>
</div>
    
		