<div class="container">
    <div class="inner10 relative content-404">
        <img src="<?php echo $this->config->asset->home_image_url . 'trang404.jpg'; ?>" alt="Tim viec nhanh">

        <div class="text1">
            Đường dẫn bạn vừa truy cập không tồn tại
        </div>

        <div class="text2">
            Mời bạn truy cập:
        </div>
        <a href="<?php echo $this->config->static->home_url . 'viec-lam/tim-kiem-nang-cao'; ?>" class="link-ntv" title="Tìm kiếm việc làm">
            Tìm kiếm việc làm
        </a>
        <a href="<?php echo $this->config->static->home_url . 'ho-so-tim-viec/tim-kiem-nang-cao'; ?>" class="link-ntd" title="Tìm kiếm hồ sơ tìm việc">
            Tìm kiếm hồ sơ tìm việc
        </a>
    </div>

    <div class="clearfix"></div>
</div>