<link type="text/css" rel="stylesheet" href="<?php echo $this->config->asset->home_css_url . 'mobile/bootstrap.css?' . $this->config->asset->version; ?>">
<link type="text/css" rel="stylesheet" href="<?php echo $this->config->asset->home_css_url . 'mobile/owl.carousel.css?'. $this->config->asset->version; ?>">
<link type="text/css" rel="stylesheet" href="<?php echo $this->config->asset->home_css_url . 'mobile/owl.theme.css?'. $this->config->asset->version; ?>">
<link type="text/css" rel="stylesheet" href="<?php echo $this->config->asset->home_css_url . 'mobile/node.css?'. $this->config->asset->version; ?>">
<link type="text/css" rel="stylesheet" href="<?php echo $this->config->asset->home_css_url . 'mobile/font-awesome.css?'. $this->config->asset->version; ?>">
<link type="text/css" rel="stylesheet" href="<?php echo $this->config->asset->home_css_url . 'mobile/style.css?'. $this->config->asset->version; ?>">
<link type="text/css" rel="stylesheet" href="<?php echo $this->config->asset->home_css_url . 'mobile/muabannhanh.css?'. $this->config->asset->version; ?>">

<script type="text/javascript" src="<?php echo $this->config->asset->home_js_url . 'mobile/jquery-1.9.1.js?'. $this->config->asset->version; ?>"></script>
<script type="text/javascript" src="<?php echo $this->config->asset->home_js_url . 'mobile/owl.carousel.js?'. $this->config->asset->version; ?>"></script>
<script type="text/javascript" src="<?php echo $this->config->asset->home_js_url . 'mobile/bootstrap.js?'. $this->config->asset->version; ?>"></script>
<script type="text/javascript" src="<?php echo $this->config->asset->home_js_url . 'mobile/popup.js?'. $this->config->asset->version; ?>"></script>


