<!DOCTYPE html>
<?php use ITECH\Datasource\Lib\Util; ?>
<html lang="vi">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title><?php echo $title_for_layout; ?></title>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no, minimal-ui">
        <meta name="description" content="<?php echo $description_for_layout; ?>">
        <meta name="keywords" content="<?php echo $keywords_for_layout; ?>">
        <meta name="robots" content="index, follow">
        <meta name="geo.region" content="<?php echo $geo_region_for_layout; ?>">
        <meta name="geo.placename" content="<?php echo $geo_placename_for_layout; ?>">
        <meta name="geo.position" content="<?php echo $geo_position_for_layout; ?>">
        <meta name="ICBM" content="<?php echo $icbm_for_layout; ?>">
        <meta property="og:site_name" content="<?php echo $og_site_name; ?>">
        <meta property="og:title" content="<?php echo $og_title; ?>">
        <meta property="og:description" content="<?php echo $og_description; ?>">
        <meta property="og:url" content="<?php echo 'http://' . $this->request->getHttpHost() . $this->request->getServer('REQUEST_URI'); ?>">
        <meta property="og:image" content="<?php echo $og_image; ?>">
        <meta property="og:type" content="website">
        <meta property="og:type" content="article" />
        <meta property="og:locale" itemprop="inLanguage" content="vi_VN">
        <meta property="fb:admins" content="<?php echo $fb_admins_for_layout; ?>">
        <meta property="fb:app_id" content="<?php echo $social_facebook_for_layout; ?>">
        <meta name="google-signin-clientid" content="229737549315-jm6h3uo1elndmhnu6vb7vgskk8p3d978.apps.googleusercontent.com" />
        <meta name="google-signin-scope" content="https://www.googleapis.com/auth/plus.login" />
        <meta name="google-signin-requestvisibleactions" content="http://schema.org/AddAction" />
        <meta name="google-signin-cookiepolicy" content="single_host_origin" />

        <link rel="shortcut icon" href="<?php echo $this->config->asset->admin_image_url . 'favicon.jpg'; ?>">
        <link rel="image_src" href="<?php echo $this->config->asset->home_image_url . 'logo.png'; ?>">
        <link rel="canonical" href="<?php echo $canonical_layout; ?>">
        <link rel="author" href="<?php echo $social_google_for_layout; ?>">

        <?php echo $this->partial($__theme. '/element/layout/_asset'); ?>
        <script>
         (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
         (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
         m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
         })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

         ga('create', '<?php echo $google_analytics_for_layout;?>', 'auto');
         ga('send', 'pageview');

        </script>
    </head>
    <body>
        
        <?php echo $this->partial($__theme. '/element/layout/_header', array('form_l' => $form_l, 'form_r' => $form_r)); ?>
        <?php echo $this->getContent(); ?>
        <?php echo $this->partial($__theme. '/element/layout/_footer'); ?>
        <?php //echo $this->partial($__theme . '/element/layout/_script'); ?>
        <!--<?php echo round(microtime(true) - START_TIME, 3) . 's'; ?>-->
    </body>
</html>
