<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title><?php echo $title_for_layout; ?></title>

        <meta name="description" content="">
        <meta name="keywords" content="">
        <meta name="robots" content="noindex, nofollow">
        <meta name="geo.region" content="VN-SG">
        <meta name="geo.placename" content="Tầng 6, Bitexco Nam Long - 63A Võ Văn Tần, P.6, Q.3, TP.Hồ Chí Minh">
        <meta name="geo.position" content="10.777494; 106.690915">
        <meta name="ICBM" content="10.777494, 106.690915">

        <meta property="og:site_name" content="Tìm Việc Nhanh">
        <meta property="og:title" content="">
        <meta property="og:description" content="">
        <meta property="og:url" content="">
        <meta property="og:image" content="<?php echo $this->config->asset->home_image_url . 'logo_tvn_fb3.png'; ?>">
        <meta property="og:type" content="website">
        <meta property="og:locale" itemprop="inLanguage" content="vi_VN">
        <meta property="fb:admins" content="1258683322,100001490595922,100003777124873,100003752736698,100000091680510,100000866550113">
        <meta property="fb:app_id" content="357584370994953">

        <link type="image/x-icon" rel="shortcut icon" href="<?php echo $this->config->asset->admin_image_url . 'favicon.png'; ?>">
        <link type="image/x-icon" rel="icon" href="<?php echo $this->config->asset->admin_image_url . 'favicon.png'; ?>">

        <link rel="image_src" href="<?php echo $this->config->asset->home_image_url . 'logo_tvn_fb3.png'; ?>">
        <link rel="author" href="https://plus.google.com/+timviecnhanh">

        <?php echo $this->partial('user/element/layout/_asset'); ?>
    </head>
    <body>
        <header class="header-site">
            <?php echo $this->partial('user/element/layout/_header'); ?>
        </header>
        <nav class="main-nav-site">
            <?php echo $this->partial('user/element/layout/_header_navigation'); ?>
        </nav>
        <section class="body-home">
            <?php echo $this->getContent(); ?>
        </section>
        <div class="bg-info footer-hotline inner-12">
            <?php echo $this->partial('user/element/layout/_footer_hotline'); ?>
        </div>
        <nav class="menu-footer bg-primary">
			<?php echo $this->partial('user/element/layout/_footer_navigation'); ?>
		</nav>
        <div class="footer-row footer-row1">
			<?php echo $this->partial('user/element/layout/_footer_address'); ?>
		</div>
        <div class="footer-row footer-row2">
			<?php echo $this->partial('user/element/layout/_footer_more_info'); ?>
		</div>
        <nav class="menu-bottom-footer">
			<?php echo $this->partial('user/element/layout/_bottom_navigation'); ?>
		</nav>

        <div id="fb-root"></div>

        <?php echo $this->partial('user/element/layout/_script'); ?>
        <!-- <?php echo round(microtime(true) - START_TIME, 3) . 's'; ?> -->
    </body>
</html>