<?php use ITECH\Datasource\Lib\Constant; ?>

<div class="container">
    <?php echo $this->partial('element/layout/_breadcrumbs');?>
    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="panel-tools">
                    </div>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-sm-3">
                            <button class="btn btn-icon btn-block">
                                <i class="fa fa-laptop"></i>
                                Sản phẩm
                                <span class="badge badge-warning">
                                    <?php echo $count_product; ?>
                                </span>
                            </button>
                        </div>
                        <div class="col-sm-3">
                            <button class="btn btn-icon btn-block">
                                <i class="fa fa-laptop"></i>
                                Bài viết
                                <span class="badge badge-warning">
                                    <?php echo $count_article; ?>
                                </span>
                            </button>
                        </div>
                        <div class="col-sm-3">
                            <button class="btn btn-icon btn-block">
                                <i class="fa fa-shopping-cart"></i>
                                Đơn đặt hàng
                                <span class="badge badge-danger"> 
                                    <?php echo $count_order; ?>
                                </span>
                            </button>
                        </div>
                        <div class="col-sm-3">
                            <button class="btn btn-icon btn-block">
                                <i class="fa fa-shopping-cart"></i>
                                Thành viên
                                <span class="badge badge-primary"> 
                                    <?php echo $count_user; ?> 
                                </span>
                            </button>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-3">
                            <button class="btn btn-icon btn-block">
                                <i class="fa fa-picture-o"></i>
                                Hình ảnh 
                                <span class="badge badge-danger"> 
                                    <?php echo $count_file; ?>
                                </span>
                            </button>
                        </div>
                        <div class="col-sm-3">
                            <button class="btn btn-icon btn-block">
                                <i class="fa fa-heart-o"></i>
                                Favorites <span class="badge badge-danger"> 4 </span>
                            </button>
                        </div>
                        <div class="col-sm-2">
                            <button class="btn btn-icon btn-block">
                                <i class="fa fa-thumbs-up"></i>
                                Likes <span class="badge badge-warning"> 4 </span>
                            </button>
                        </div>
                        <div class="col-sm-4">
                            <button class="btn btn-icon btn-block">
                                <i class="fa fa-exclamation-triangle"></i>
                                Warning <span class="badge badge-success"> 4 </span>
                            </button>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-2">
                            <button class="btn btn-icon btn-block">
                                <i class="fa fa-tasks"></i>
                                Tasks <span class="badge badge-danger"> 4 </span>
                            </button>
                        </div>
                        <div class="col-sm-2">
                            <button class="btn btn-icon btn-block">
                                <i class="fa fa-check"></i>
                                To Do <span class="badge badge-success"> 4 </span>
                            </button>
                        </div>
                        <div class="col-sm-2">
                            <button class="btn btn-icon btn-block">
                                <i class="fa fa-list"></i>
                                Tickets <span class="badge badge-warning"> 4 </span>
                            </button>
                        </div>
                        <div class="col-sm-3">
                            <button class="btn btn-icon btn-block">
                                <i class="fa fa-calendar"></i>
                                Calendar <span class="badge badge-success"> 4 </span>
                            </button>
                        </div>
                        <div class="col-sm-2">
                            <button class="btn btn-icon btn-block">
                                <i class="fa fa-upload"></i>
                                Upload <span class="badge badge-success"> 4 </span>
                            </button>
                        </div>
                        <div class="col-sm-2">
                            <button class="btn btn-icon btn-block">
                                <i class="fa fa-tags"></i>
                                Tags <span class="badge badge-danger"> 4 </span>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>