<div class="form-group">
    <label class="col-sm-2 control-label">
    Tiêu đề    
    </label>
    <div class="col-sm-4">
        <?php echo $form->render('title', array('class' => 'form-control')); ?>
        <?php echo $this->partial('element/layout/_message', array('form' => $form, 'element' => 'title')); ?>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label">
        Hình ảnh
    </label>
    <div class="col-sm-9">
        <?php if ($file->file_name != ''): ?> 
            <img src="<?php echo $this->config->asset->home_image_url . '150/' . $file->file_name; ?>">           
        <?php else: ?>
            <img src="<?php echo $this->config->asset->home_image_url . 'default.gif'; ?>">
        <?php endif; ?>   
        <?php echo $form->render('file_name', array('class' => 'form-control' ,'id' => 'img-file', 'style' => 'display: none')); ?>
            <br>
            <br>
            <div>
                <a onclick="$('#img-file').click();" id="choose-button" class="upload-avatar modelbox btn-grey btn btn-big w117">
                    <span class="icon icon-sm icon-image"></span><span class="text">Chọn hình ảnh</span>
                </a>
                <?php echo $this->partial('element/layout/_message', array('form' => $form, 'element' => 'file_name')); ?>
                <script type="text/javascript">
                    $(document).ready(function() {
                        $('#img-file').change(function() {
                            $('img-file').value =
                            $('#choose-button').html('<span class="icon icon-sm icon-image"></span><span class="text">Đã chọn</span>');
                        });
                    });
                </script>
            </div>
              
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label">
        Thư mục
    </label>
    <div class="col-sm-4">
        <?php echo $category_layout; ?>
    </div>
</div>