<?php use ITECH\Datasource\Lib\Constant; ?>

<?php
    switch ($from) {
        case 'article':
            $image_url = $this->config->asset->home_image_url . '150/';
            break;
        case 'product':
            $image_url = $this->config->asset->home_image_url . '150/';
            break;
        case 'page':
            $image_url = $this->config->asset->home_image_url . '150/';
            break;
    }
?>
<div class="panel panel-default">
    <div class="panel-heading">
        <i class="fa fa-cogs"></i>
        Danh sách gallery
        <div class="panel-tools">
            <a class="btn btn-xs btn-link panel-collapse collapses" href="#">
            </a>
        </div>
    </div>
    <div class="panel-body">
        <form action="" method="POST" enctype="multipart/form-data">
            <table class="table table-striped table-bordered table-hover table-full-width">
                <thead>
                    <tr role="row">
                        <th>STT</th>
                        <th>Tiêu đề</th>
                        <th>Alt</th>
                        <th>Hình ảnh</th>
                        <th>Mô tả</th>
                        <th>Dung lượng</th>
                        <th>Hình ảnh</th>
                        <th></th>
                    </tr>
                </thead>

                <tbody>
                    <?php foreach ($article_attachments as $file): ?>
                        <?php
                        $query = array(
                            'id' => $file->id,
                            'page' => $page,
                            'q' => $q,
                            'cache_name' => $cache_name,
                            'from' => $from
                        );
                        ?>
                        <tr>
                            <td><?php echo $file->id; ?></td>
                            <td>
                                <a href="<?php echo $this->url->get(array('for' => 'file_gallery_edit', 'query' => '?' . http_build_query($query))); ?>">
                                    <?php echo $file->title; ?>
                                </a>
                            </td>
                            <td>
                                <?php echo $file->alternative; ?>
                            </td>
                            <td>
                                <img src="<?php echo $this->config->asset->home_image_url . '150/' . $file->file_name; ?>" alt="<?php echo $file->title; ?>" >
                            </td>
                            <td>
                                <?php echo $file->description; ?>
                            </td>
                            <td>
                                <?php 
                                echo round($file->file_size/102400, 3) . 'Mb'; 
                                ?>
                            </td>
                            <td>
                                <input type="text" name="ordering[<?php echo $file->id; ?>]" class="form-control input-sm w50" autocomplete="off" value="<?php echo $file->ordering; ?>" />
                            </td>
                            <td align="center">
                                <a href="<?php echo $this->url->get(array('for' => 'file_gallery_delete_image', 'query' => '?' . http_build_query($query))); ?>" onclick="javascript:return confirm('Đồng ý xoá?');" class="btn btn-xs btn-bricky">
                                    <i class="fa fa-times fa fa-white"></i>
                                </a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>
                            <button type="submit" class="btn btn-sm btn-blue">
                                Cập nhật
                            </button>
                        </td>
                        <td></td>
                    </tr>    
                </tbody>
            </table>
            <input type="hidden" name="<?php echo $this->security->getTokenKey(); ?>" value="<?php echo $this->security->getToken(); ?>" />
        </form>
    </div>
</div>
    