<?php use ITECH\Datasource\Lib\Constant; ?>

<?php
$query = array(
    'page' => $page,
    'q' => $q
);
?>

<div class="container">
    <?php echo $this->partial('element/layout/_breadcrumbs');?>
    <form id="form" role="form" action="" method="POST" enctype="multipart/form-data" class="form-horizontal">
        <?php echo $this->flashSession->output(); ?>
        <?php echo $this->partial('file/_form_category'); ?>
        <div class="form-group">
            <label class="col-sm-2 control-label"></label>
            <div class="col-sm-9">
                <button type="submit" class="btn btn-bricky">
                    Cập nhật
                </button>
                <a href="<?php echo $this->url->get(array('for' => 'file_category', 'query' => '?' . http_build_query($query))); ?>" class="btn btn-primary">
                    Trở lại
                </a>
            </div>
        </div>

        <?php if ($category->status != Constant::CATEGORY_STATUS_DELETED): ?>
            <?php
            $query = array(
                'id' => $category->id,
                'page' => $page,
                'q' => $q,
                'cache_name' => $cache_name
            );
            ?>
            <div class="form-group">
                <label class="col-sm-2 control-label"></label>
                <div class="col-sm-9 text-right">
                    <a href="<?php echo $this->url->get(array('for' => 'file_category_delete', 'query' => '?' . http_build_query($query))); ?>" onclick="javascript:return confirm('Đồng ý xoá?');" class="btn btn-primary">
                        Xóa
                    </a>
                </div>
            </div>
        <?php endif; ?>

        <input type="hidden" name="<?php echo $this->security->getTokenKey(); ?>" value="<?php echo $this->security->getToken(); ?>">
    </form>
</div>