<div class="form-group">
    <label class="col-sm-2 control-label">
        Tiêu đề
    </label>
    <div class="col-sm-9">
        <?php echo $form->render('title', array('class' => 'form-control')); ?>
        <?php echo $this->partial('element/layout/_message', array('form' => $form, 'element' => 'title')); ?>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label">
        Meta title
    </label>
    <div class="col-sm-9">
        <?php echo $form->render('meta_title', array('class' => 'form-control')); ?>
        <?php echo $this->partial('element/layout/_message', array('form' => $form, 'element' => 'meta_title')); ?>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label">
        Meta description
    </label>
    <div class="col-sm-9">
        <?php echo $form->render('meta_description', array('class' => 'form-control')); ?>
        <?php echo $this->partial('element/layout/_message', array('form' => $form, 'element' => 'meta_description')); ?>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label">
        Meta keyword
    </label>
    <div class="col-sm-9">
        <?php echo $form->render('meta_keyword', array('class' => 'form-control')); ?>
        <?php echo $this->partial('element/layout/_message', array('form' => $form, 'element' => 'meta_keyword')); ?>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label">
        Title h2 :
    </label>
    <div class="col-sm-9">
        <?php echo $form->render('tags_h2', array('class' => 'form-control')); ?>
        <?php echo $this->partial('element/layout/_message', array('form' => $form, 'element' => 'tags_h2')); ?>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label">
        Nội Dung h2 :
    </label>
    <div class="col-sm-9">
        <?php echo $form->render('tags_content_2', array('class' => 'form-control editor')); ?>
        <?php echo $this->partial('element/layout/_message', array('form' => $form, 'element' => 'tags_content_2')); ?>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label">
        Title h3 :
    </label>
    <div class="col-sm-9">
        <?php echo $form->render('tags_h3', array('class' => 'form-control')); ?>
        <?php echo $this->partial('element/layout/_message', array('form' => $form, 'element' => 'tags_h3')); ?>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label">
        Nội Dung h3 :
    </label>
    <div class="col-sm-9">
        <?php echo $form->render('tags_content_3', array('class' => 'form-control editor')); ?>
        <?php echo $this->partial('element/layout/_message', array('form' => $form, 'element' => 'tags_content_3')); ?>
    </div>
</div>