<?php
$query = array(
    'page' => $page,
    'q' => $q,
    'cache_name' => $cache_name
);
?>

<div class="container">
    <?php echo $this->partial('element/layout/_breadcrumbs');?>

    <form id="form" role="form" action="" method="POST" enctype="multipart/form-data" class="form-horizontal">
        <?php echo $this->flashSession->output(); ?>
        <?php echo $this->partial('category/_attribute_group_form'); ?>

        <div class="form-group">
            <label class="col-sm-2 control-label"></label>
            <div class="col-sm-9">
                <button type="submit" class="btn btn-bricky">
                    Cập nhật
                </button>
                <a href="<?php echo $this->url->get(array('for' => 'category_attribute_group', 'query' => '?' . http_build_query($query))); ?>" class="btn btn-primary">
                    Trở lại
                </a>
            </div>
        </div>
        <input type="hidden" name="<?php echo $this->security->getTokenKey(); ?>" value="<?php echo $this->security->getToken(); ?>">
    </form>
</div>