<?php use ITECH\Datasource\Lib\Constant; ?>

<?php $module = Constant::statusSelect(); ?>
<?php 
$query = array(
    'page' => $page,
    'q' => $q,
    'cache_name' => $cache_name
);
?>
<div class="container">
    <?php echo $this->partial('element/layout/_breadcrumbs'); ?>
    <?php echo $this->flashSession->output(); ?>
    <div class="text-right">
        <a class="btn btn-primary" href="<?php echo $this->url->get(array('for' => 'category_tag_add', 'query' => '?' . http_build_query($query))); ?>"> Thêm tag </a>
    </div>
    <p></p>
    <?php echo $this->partial('category/_tag_list'); ?>
    <?php
    echo $this->partial('element/layout/_pagination', array(
        'result' => $result,
        'for' => 'category_tag',
        'query' => array(
        'page' => $page,
        'q' => $q
        )
    ));
    ?>
</div>